### ISSUE TITLE
예외 처리 핸들러 구현

### ISSUE THREAD

**Issue by csct3434** [goormthon-Univ/TEAM_1#2]
## 💡 Issue: 이슈 요약
RestControllerAdvice를 활용한 전역 예외 처리 핸들러를 구현합니다.

## 📝 Todo: 할 작업
- [x] 커스텀 예외 클래스 작성
- [x] 커스텀 오류 응답 클래스 작성
- [x] 전역 예외 처리 핸들러 구현
