### ISSUE TITLE
기록장 등록 기능 구현

### ISSUE THREAD

**Issue by csct3434** [goormthon-Univ/TEAM_1#25]
## 💡 Issue: 이슈 요약
기록장 등록 기능 구현

## 📝 Todo: 할 작업
- [ ] 기록장 엔티티 작성
- [ ] 기록장 등록 서비스 구현
- [ ] 기록장 등록 웹 API 구현
